### ISSUE TITLE
Doesn't work with ES6 imports and TypeScript

### ISSUE THREAD

**Issue by IGassmann** [cdimascio/uuid-mongodb#12]
The following throws the compilation error `'MUUID' only refers to a type, but is being used as a value here.`

```
import { MUUID } from 'uuid-mongodb';

const muuid = MUUID.from('393967e0-8de1-11e8-9eb6-529269fb1459');
```

**Comment by cdimascio** [comment]
To import MUUID with Typescript, you can do one of the following:

```
import * as MUUID from 'uuid-mongodb'
```

or set tsconfig.json `compilerOptions.esModuleInterop: true`
and do the following

```
import MUUID from 'uuid-mongodb'
```

**Comment by cdimascio** [comment]
@IGassmann see above comment

**Comment by IGassmann** [comment]
Thanks!
