### ISSUE TITLE
Hex uuids in JSON

### ISSUE THREAD

**Issue by irothschild** [cdimascio/uuid-mongodb#19]
I was surprised that JSON.stringify on my MUUIDs generated base64 and not hex. To fix this I forked the repo and added `mu.toJSON = mu.toString;` to the `apply()` function. I could do a PR but I'm not sure if people are counting on the base64 behavior.

**Comment by cdimascio** [comment]
@irothschild This [PR](https://github.com/cdimascio/uuid-mongodb/pull/15) adds formatting. Perhaps, a hex option makes sense.

**Comment by cdimascio** [comment]
@irothschild please submit a PR. It will be great to review and potentially get your work merged in

**Comment by cdimascio** [comment]
That PR uses microsoft formatting values

N | 32 digits:00000000000000000000000000000000
-- | --
D | 32 digits separated by hyphens:00000000-0000-0000-0000-000000000000
B | 32 digits separated by hyphens, enclosed in braces:{00000000-0000-0000-0000-000000000000}
P | 32 digits separated by hyphens, enclosed in parentheses:(00000000-0000-0000-0000-000000000000)
X | Four hexadecimal values enclosed in braces, where the fourth value is a subset of eight hexadecimal values that is also enclosed in braces:{0x00000000,0x0000,0x0000,{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}}

It would be nice to add your work to enable the `X` hex option

**Comment by cdimascio** [comment]
I presume `X` is the output style you are looking for?

**Comment by cdimascio** [comment]
Note the PR above has been merged and available in `v2.2.0` see README for details.
Curious, might your PR provide formatting for `X` above?

**Comment by irothschild** [comment]
No, my fix is only for JSON.stringify() and does format N (actually whatever toString() does.)

Current version:
```
> JSON.stringify(MUUID.v4())
'"j5BkgdehQ/OH9H5BX0re2g=="'
```

My version:
```
> JSON.stringify(MUUID.v4())
'"35186504-d49a-4f5e-8d83-8c51b1727204"'
```

It's not even one line of code. Just change line 90 to assign to `mu.toJSON` as well as `mu.toString` in `apply(mu)`:

```
function apply(mu) {
  // add to string method                                                                             
  // formatting parameter (optional) follows the behavior of Microsoft's UUID string function: https:\
//docs.microsoft.com/en-us/dotnet/api/system.guid.tostring                                            
  mu.toJSON = mu.toString = function (format) {
....
```

**Comment by cdimascio** [comment]
The mongo Binary type itself returns base64 for a Binary uuid type
```
> JSON.stringify(Binary(uuid, Binary.SUBTYPE_UUID))
'"mv57IIXCEeq/13Ecmt7j5w=="'
```

Given that the MongoDB driver for Node.js returns base64, base64 should remain the default behavior for this library to ensure consistency.

Can you describe your use case in more detail? Is `toString()` sufficient to solve it. Ultimately, toString() provides the behavior you want.

**Comment by irothschild** [comment]
MongoDB is using the BSON Binary type which implements:

```
Binary.prototype.toJSON = function() {
  return this.buffer != null ? this.buffer.toString('base64') : '';
};
```

However, since BSON is binary over the wire, I don't think it uses JSON.stringify() internally other than for logging.

The reason I want the uuids in hex is so that when I JSON.stringify() a model containing uuid fields, it produces nice hex uuid strings. I looked at using a JSON.stringify replacer but since Binary implements toJSON, by the time the value gets passed to the replacer, it's already a b64 string. I think the only other option is to transform my model before stringifying, which I wanted to avoid.

I have had no problems since I've made the change but I understand if you don't want to put it in your module.

**Comment by cdimascio** [comment]
@irothschild thanks for the details. Could you provide the snippet of the change you made? 

At the least, it may be worth including it in the README as it may help others that encounter a similar situation.

**Comment by irothschild** [comment]
Change line 90 to assign to mu.toJSON as well as mu.toString in apply(mu):

function apply(mu) {
...
  mu.toJSON = mu.toString = function (format) {         // <------- this line
...

**Comment by cdimascio** [comment]
@irothschild i've added support for you feature request. MongoDB has a notion of canonical and relaxed modes. I've introduced that same notion here.

Please see the README for details. 
I will roll a new version momentairly

**Comment by cdimascio** [comment]
this feature is supported inn `v2.3.0`

uuid-mongodb offers two modes, canonical (default) and relaxed.

- canonical - A string format that emphasizes type preservation at the expense of readability and interoperability.
- relaxed - A string format that emphasizes readability and interoperability at the expense of type preservation.
Modes are set globally. here is how set the mode

```javascript
const mUUID = MUUID.mode('relaxed'); // use relaxed mode
```

**Comment by irothschild** [comment]
Thanks!
