### ISSUE TITLE
Mongoose Example in Docs

### ISSUE THREAD

**Issue by alokrajiv** [cdimascio/uuid-mongodb#8]
[NOT A BUG] Just a documentation request.

Considering that even in the package.json since its written that the plugin is fully compatible with Mongoose, it would be helpful if a simple Schema example for Mongoose can be added here.

**Comment by cdimascio** [comment]
Thanks for the issues @alokrajiv. 
A Mongoose example is now available in the [README](https://github.com/cdimascio/uuid-mongodb#Native-Node-MongoDB-Driver-example)
full example source code [here](https://github.com/cdimascio/uuid-mongodb/blob/master/example/ex2-mongoose.js)

**Comment by alokrajiv** [comment]
@cdimascio hi, thanks for that. Btw, We've been using Buffer. Any reason you used Mixed specifically? Got the idea from Mongoose Docs preferred type for Binary. ([Doc's Link](https://mongoosejs.com/docs/schematypes.html))

**Comment by cdimascio** [comment]
@alokrajiv, you're right. Buffer is the better choice. I will update the doc. Feel free to post your example here for reference. Thanks!

**Comment by alokrajiv** [comment]
@cdimascio I did a PR with just the schema change. I have a more advanced use case- with virtual setters and getter for string representation for APIs and Views :) 

But, I think the simple example you already have should suffice right?
